
/* Turbomachinery and Unsteady Flows Research Group | University of Windsor  *\
                    ░░▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒░░░                                 
                 ░▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒░                            
               ░▒▓▓▒▒░░░░▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒░                      
             ░▒▓▓░   ▒▓░    ░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░                  
            ▒▓▓░   ░▒▓▓▓░ ░▓▓▓▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒░               
           ▒▓▒░░░  ░▓▓▓▓▒░▓▓▓▓▒░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒░            
         ░▓▓▒ ░░░░ ░▓▓▓▓▓ ▒▓▓▓▒  ▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒          
         ▒▓▒  ░░░░░ ▒▓▓▓▓░░▓▓▓▒  ░▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒        
        ▓▓▒   ░░░░░░░▓▓▓▓░░▓▓▓▒                        ░░▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓░      
       ▒▓▓░   ░░░░░░ ░▓▓▓▒ ▓▓▓▒       ░░░▒▒▒▒▒▒▒▒▒░░░░          ░░░▒▓▓▓▓▓░     
      ▒▓▓▒░    ░░░░░░ ▒▓▓▒ ▒▓▓▒ ░▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒░░     ▒░     
      ▓▓▓░▓▓▒    ░░░░ ░▓▓▓░▒▓▓▒  ░▓▓▓▓▒░  ▒▓▓▒                   ░▒▒▓▓▓▓▒      
     ▒▓▓░▒▓▓▓▓░   ░░░░ ▒▓▓░░▓▓▒           ▒▓▓▒    ░                      ░░▒▒░ 
    ░▓▓▒ ▒▓▓▓▓▓▒   ░░░░░▓▓░░▓▓▒           ▒▓▓▒    ▒▓  ▒▓░▒▓▓▓▒ ▓▓▓▓░  ░▓▓░     
    ▒▓▓░ ▒▓▓▓▓▓▓▓░  ░░░ ▒▓▒░▓▓░           ▒▓▓▒   ░▒▓  ▓▓░▒▓░   ▓▒░▒▓░▒▓▒░▓▒░   
   ░▒▓▒░ ▒▓▓▓▓▓▓▓▓░ ░░░░░▓▒░▓▓░           ▒▓▓▒   ░▒▓  ▓▓░▒▓▓▓░ ▓▒░▒▓ ▒▓░       
   ░▓▓▒    ░▒▓▓▓▓▓▓▒ ░░░ ▓░░▓▓            ▒▓▓▒   ░▒▓  ▓▒░▒▓░   ▓▓▓▓▒░▒▓░░▓▓░   
   ▒▓▓▒       ░▒▓▓▓▓▒ ░░ ▒░░▓░            ▒▓▓▒   ░▒▓ ░▓▒░▒▓░   ▓▓ ▒▓░▒▓▓▓▓▓░   
   ▒▓▓░▒▒▒░░░    ▒▓▓▓░                    ▒▓▓▒    ░▓▓▓▓░ ▒▓░   ▓▓ ░▓▓  ▓▓      
   ▓▓▓░▓▓▓▓▓▓▓▓▒  ░▒▓░   ░░               ▒▓▓▒                          ░▒▒▒▒░ 
  ░▓▓▓░▓▓▓▓▓▓▓▓▓▓▒░ ░  ░▓▓▓▓▓▓▒▒░░░       ░░░░               ░░░░▒▒▒▓▓▓▒▒░░    
  ░▓▓▒░▓▓▓▓▓▓▓▓▓▓▓▓░  ░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒░            
  ░▒▒░                   ░░▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░                   
\*---------------------------------------------------------------------------*/

    // Initialize quantities for BF calculations which are constants
    
	const volVectorField& C = mesh.C(); // cell centre coordinates

	const dimensionedScalar smallLength
	(
		"smallLength",
		dimensionSet(0,1,0,0,0,0,0),
		scalar(1e-4)
	); // This is for comparisons with the radius to avoid divide-by-zero issues

	const dimensionedScalar smallVelocity
	(
		"smallVelocity",
		dimensionSet(0,1,-1,0,0,0,0),
		scalar(1e-5)
	); // This is for comparisons with the relative velocity to avoid divide-by-zero issues

	const dimensionedScalar one
	(
		"one",
		dimensionSet(0,2,0,0,0,0,0),
		scalar(1.0)
	);
	volScalarField fOutVal("fOutVal", sqr(chordwisePos)/(one+sqr(chordwisePos)));
	volScalarField fOut("fOut", 0.0*fOutVal);
	forAll(fOut,i)
	{
	//	fOut[i]=min(ceil(sqr(chordwisePos[i])/(sqr(chordwisePos[i]) + 1)), 1.0); //when chordwisePos is 0 fOut is 0 otherwise fOut is 1
		fOut[i]=ceil(fOutVal[i]);
	}
	
	// turbomachinery parameters, read from constant/BFcontrolsDict
	tensor Rot;
	BFcontrols.lookup("Rot") >> Rot;
	scalar FpCalibrated;
	BFcontrols.lookup("calibrationMode") >> FpCalibrated;
	FpCalibrated = 1.0 - FpCalibrated;

	// thermodynamic properties -- from thermo model (assumes perfect gas)
	const volScalarField& tCp = thermo.Cp();
	const dimensionedScalar Cp = max(tCp.internalField());
	const volScalarField& tCv = thermo.Cv();
	const dimensionedScalar Cv = max(tCv.internalField());
	const dimensionedScalar Rgas = Cp - Cv;
	const dimensionedScalar gamma = Cp / Cv;
	
	// define intermediate properties -- these don't change as the solution
	// progresses so they can be calculated here, before the time loop starts
	const tensor Rot1 = Rot.T();
	volVectorField abc("abc", Rot & C); // abc coordinates
	volScalarField Radius("Radius", max(sqrt(sqr(abc.component(0)) + sqr(abc.component(1))),smallLength));
	volScalarField THETA("THETA", atan2(abc.component(1), abc.component(0)));

	tensor TmatCosMask(0,1, 0,0,0,1,0,0,0);
	tensor TmatSinMask(0,0,-1,0,1,0,0,0,0);
	tensor TmatOneMask(0,0, 0,0,0,0,1,0,0);
	volTensorField Tmatrix = cos(THETA)*TmatCosMask + sin(THETA)*TmatSinMask + TmatOneMask;
		// update the above lines if order of coordinates in camber fixed.
		// Currently assumes camber has elements (c,r,theta)
		// SHOULD be (r,theta,c)	
	nabc = Tmatrix & camber;

	// Initialze mass source term
	volScalarField Sb("Sb", rho * U & fvc::grad(b) / b);
