
/* Turbomachinery and Unsteady Flows Research Group | University of Windsor  *\
                    ░░▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒░░░                                 
                 ░▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒░                            
               ░▒▓▓▒▒░░░░▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒░                      
             ░▒▓▓░   ▒▓░    ░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░                  
            ▒▓▓░   ░▒▓▓▓░ ░▓▓▓▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒░               
           ▒▓▒░░░  ░▓▓▓▓▒░▓▓▓▓▒░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒░            
         ░▓▓▒ ░░░░ ░▓▓▓▓▓ ▒▓▓▓▒  ▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒          
         ▒▓▒  ░░░░░ ▒▓▓▓▓░░▓▓▓▒  ░▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒        
        ▓▓▒   ░░░░░░░▓▓▓▓░░▓▓▓▒                        ░░▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓░      
       ▒▓▓░   ░░░░░░ ░▓▓▓▒ ▓▓▓▒       ░░░▒▒▒▒▒▒▒▒▒░░░░          ░░░▒▓▓▓▓▓░     
      ▒▓▓▒░    ░░░░░░ ▒▓▓▒ ▒▓▓▒ ░▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒░░     ▒░     
      ▓▓▓░▓▓▒    ░░░░ ░▓▓▓░▒▓▓▒  ░▓▓▓▓▒░  ▒▓▓▒                   ░▒▒▓▓▓▓▒      
     ▒▓▓░▒▓▓▓▓░   ░░░░ ▒▓▓░░▓▓▒           ▒▓▓▒    ░                      ░░▒▒░ 
    ░▓▓▒ ▒▓▓▓▓▓▒   ░░░░░▓▓░░▓▓▒           ▒▓▓▒    ▒▓  ▒▓░▒▓▓▓▒ ▓▓▓▓░  ░▓▓░     
    ▒▓▓░ ▒▓▓▓▓▓▓▓░  ░░░ ▒▓▒░▓▓░           ▒▓▓▒   ░▒▓  ▓▓░▒▓░   ▓▒░▒▓░▒▓▒░▓▒░   
   ░▒▓▒░ ▒▓▓▓▓▓▓▓▓░ ░░░░░▓▒░▓▓░           ▒▓▓▒   ░▒▓  ▓▓░▒▓▓▓░ ▓▒░▒▓ ▒▓░       
   ░▓▓▒    ░▒▓▓▓▓▓▓▒ ░░░ ▓░░▓▓            ▒▓▓▒   ░▒▓  ▓▒░▒▓░   ▓▓▓▓▒░▒▓░░▓▓░   
   ▒▓▓▒       ░▒▓▓▓▓▒ ░░ ▒░░▓░            ▒▓▓▒   ░▒▓ ░▓▒░▒▓░   ▓▓ ▒▓░▒▓▓▓▓▓░   
   ▒▓▓░▒▒▒░░░    ▒▓▓▓░                    ▒▓▓▒    ░▓▓▓▓░ ▒▓░   ▓▓ ░▓▓  ▓▓      
   ▓▓▓░▓▓▓▓▓▓▓▓▒  ░▒▓░   ░░               ▒▓▓▒                          ░▒▒▒▒░ 
  ░▓▓▓░▓▓▓▓▓▓▓▓▓▓▒░ ░  ░▓▓▓▓▓▓▒▒░░░       ░░░░               ░░░░▒▒▒▓▓▓▒▒░░    
  ░▓▓▒░▓▓▓▓▓▓▓▓▓▓▓▓░  ░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒░            
  ░▒▒░                   ░░▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░                   
\*---------------------------------------------------------------------------*/

    // Calculate F again

	Uabc = Rot & U;
	Wabc = Uabc - (OMEGA ^ abc);

	// Normal force
	DEVLOC = asin(max(min((Wabc & nabc) / max(mag(Wabc), smallVelocity),dimensionedScalar("1", dimless, 1.0)),dimensionedScalar("-1", dimless, -1.0)));
//	DEVLOC = asin((Wabc & nabc) / max(mag(Wabc),smallVelocity));
	WabcN = (Wabc & nabc) * nabc;
	WabcT = Wabc - WabcN;
	tabc = WabcT / max(mag(WabcT), smallVelocity);
	//fnmag = 0.5*DEVLOC*magSqr(Wabc)*BR/max(Radius,smallLength)/max(mag(camber.component(2)),1e-4);
	//fnmag = 0.5*DEVLOC*magSqr(Wabc)*B/max(Radius,smallLength)/max(mag(camber.component(2)),1e-4);
//	fnmag = 0.5*DEVLOC*magSqr(Wabc)*B/max(Radius,smallLength)/max(mag(camber.component(2)),1e-4);
	fnmag = Foam::constant::mathematical::pi*DEVLOC*magSqr(Wabc)/max(Radius,smallLength)/max(mag(pitch),1e-4)/(max(mag(camber.component(2)),1e-4));
	// Compressibility correction on normal force
	Mrel = mag(Wabc)/sqrt(gamma*Rgas*tT);
	forAll(SS,i)
	{
		SS[i]=min(floor(Mrel[i]-(1.0e-4)),1.0); // mask field for supersonic flow (0 = Mrel<1, 1 = Mrel>=1)
	}
	// the tiny offset is to avoid problems when Mrel = 1.0 exactly
	KNR = (1.0-SS) * (1.0/Foam::sqrt(mag(1.0 - magSqr(Mrel)))) + SS * (4.0/Foam::constant::mathematical::pi)*(1.0/Foam::sqrt(mag(magSqr(Mrel) - 1.0)));
	fn = min(KNR,3.0) * (fnmag*sin(DEVLOC)*tabc - fnmag*cos(DEVLOC)*nabc);

	// Viscous profile loss force
	RExc = max(rho*mag(Wabc)*chordwisePos/tmu,10.0);
	Kp0 = 2.0*0.0592*pow(RExc, -0.2);

//	fpv = -1.0*magSqr(Wabc)*B/(4.0*Foam::constant::mathematical::pi*Radius*max(mag(camber.component(2)),1e-4)) * Wabc / max(mag(Wabc),smallVelocity) * (Kp0 + FpCalibrated*2.0*Foam::constant::mathematical::pi*sqr(DEVLOC-Devloc0));
	fpv = -1.0*magSqr(Wabc)/(2.0*max(Radius,smallLength)*max(mag(pitch),1e-4)*max(mag(camber.component(2)),1e-4)) * Wabc / max(mag(Wabc),smallVelocity) * (Kp0 + FpCalibrated*2.0*Foam::constant::mathematical::pi*sqr(DEVLOC-Devloc0)); // if order of camber components fixed, change index here

	// Shock loss force
	ptrel = p * pow(1.0 + (gamma-1.0)*0.5*sqr(Mrel),gamma/(gamma-1.0));
//	fps = -SS*ptrel*gammaTerm*Foam::pow((sqr(Mrel)-1.0),3.0)*B/(2.0*Foam::constant::mathematical::pi*max(Radius,smallLength)*max(mag(camber.component(2)),1e-4)*rho) * (Wabc / (max(mag(Wabc),smallVelocity))); // if order of camber components fixed, change index here
	fps = -SS*ptrel*gammaTerm*Foam::pow((sqr(Mrel)-1.0),3.0)/(max(Radius,smallLength)*max(mag(pitch),1e-4)*max(mag(camber.component(2)),1e-4)*rho) * (Wabc / (max(mag(Wabc),smallVelocity))); 
	
	fabc = fn + fpv + fps;	
	fxyz = Rot1 & fabc;
	
	// compute F
	F = (rho * fxyz / b) * fOut;
