
/* Turbomachinery and Unsteady Flows Research Group | University of Windsor  *\
                    ░░▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒░░░                                 
                 ░▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒░                            
               ░▒▓▓▒▒░░░░▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒░                      
             ░▒▓▓░   ▒▓░    ░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░                  
            ▒▓▓░   ░▒▓▓▓░ ░▓▓▓▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒░               
           ▒▓▒░░░  ░▓▓▓▓▒░▓▓▓▓▒░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒░            
         ░▓▓▒ ░░░░ ░▓▓▓▓▓ ▒▓▓▓▒  ▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒          
         ▒▓▒  ░░░░░ ▒▓▓▓▓░░▓▓▓▒  ░▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒        
        ▓▓▒   ░░░░░░░▓▓▓▓░░▓▓▓▒                        ░░▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓░      
       ▒▓▓░   ░░░░░░ ░▓▓▓▒ ▓▓▓▒       ░░░▒▒▒▒▒▒▒▒▒░░░░          ░░░▒▓▓▓▓▓░     
      ▒▓▓▒░    ░░░░░░ ▒▓▓▒ ▒▓▓▒ ░▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒░░     ▒░     
      ▓▓▓░▓▓▒    ░░░░ ░▓▓▓░▒▓▓▒  ░▓▓▓▓▒░  ▒▓▓▒                   ░▒▒▓▓▓▓▒      
     ▒▓▓░▒▓▓▓▓░   ░░░░ ▒▓▓░░▓▓▒           ▒▓▓▒    ░                      ░░▒▒░ 
    ░▓▓▒ ▒▓▓▓▓▓▒   ░░░░░▓▓░░▓▓▒           ▒▓▓▒    ▒▓  ▒▓░▒▓▓▓▒ ▓▓▓▓░  ░▓▓░     
    ▒▓▓░ ▒▓▓▓▓▓▓▓░  ░░░ ▒▓▒░▓▓░           ▒▓▓▒   ░▒▓  ▓▓░▒▓░   ▓▒░▒▓░▒▓▒░▓▒░   
   ░▒▓▒░ ▒▓▓▓▓▓▓▓▓░ ░░░░░▓▒░▓▓░           ▒▓▓▒   ░▒▓  ▓▓░▒▓▓▓░ ▓▒░▒▓ ▒▓░       
   ░▓▓▒    ░▒▓▓▓▓▓▓▒ ░░░ ▓░░▓▓            ▒▓▓▒   ░▒▓  ▓▒░▒▓░   ▓▓▓▓▒░▒▓░░▓▓░   
   ▒▓▓▒       ░▒▓▓▓▓▒ ░░ ▒░░▓░            ▒▓▓▒   ░▒▓ ░▓▒░▒▓░   ▓▓ ▒▓░▒▓▓▓▓▓░   
   ▒▓▓░▒▒▒░░░    ▒▓▓▓░                    ▒▓▓▒    ░▓▓▓▓░ ▒▓░   ▓▓ ░▓▓  ▓▓      
   ▓▓▓░▓▓▓▓▓▓▓▓▒  ░▒▓░   ░░               ▒▓▓▒                          ░▒▒▒▒░ 
  ░▓▓▓░▓▓▓▓▓▓▓▓▓▓▒░ ░  ░▓▓▓▓▓▓▒▒░░░       ░░░░               ░░░░▒▒▒▓▓▓▒▒░░    
  ░▓▓▒░▓▓▓▓▓▓▓▓▓▓▓▓░  ░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒░            
  ░▒▒░                   ░░▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░                   
\*---------------------------------------------------------------------------*/

    // Set F
    
	volVectorField Uabc("Uabc", Rot & U); // velocity field in abc coordinates -- THIS SEEMS OK
	volVectorField Wabc("Wabc", Uabc - (OMEGA ^ abc)); // relative velocity in abc

	// Normal force	
	//volScalarField DEVLOC("DEVLOC", asin((Wabc & nabc) / max(mag(Wabc),smallVelocity))); // local deviation	

	volScalarField asinArg((Wabc & nabc) / max(mag(Wabc), smallVelocity));
	asinArg = max(min(asinArg, scalar(1.0)), scalar(-1.0));

	volScalarField DEVLOC("DEVLOC",asin(max(min((Wabc & nabc) / max(mag(Wabc), smallVelocity),dimensionedScalar("1", dimless, 1.0)), dimensionedScalar("-1", dimless, -1.0))));
	volVectorField WabcN("WabcN", (Wabc & nabc) * nabc); // part of Wabc in nabc direction
	volVectorField WabcT("WabcT", Wabc - WabcN); // rest of Wabc
	volVectorField tabc("tabc", WabcT/max(mag(WabcT),smallVelocity)); // tangential direction

	//volScalarField fnmag("fnmag", 0.5*DEVLOC*magSqr(Wabc)*B/max(Radius,smallLength)/(max(mag(camber.component(2)),1e-4))); // if order of camber components fixed, change index here
	volScalarField fnmag("fnmag", Foam::constant::mathematical::pi*DEVLOC*magSqr(Wabc)/max(Radius,smallLength)/max(mag(pitch),1e-4)/(max(mag(camber.component(2)),1e-4)));
	
	// Compressibility correction on normal force
	const volScalarField& tT = mesh.lookupObject<volScalarField>("T");
	volScalarField Mrel("Mrel", mag(Wabc)/sqrt(gamma*Rgas*tT));
	volScalarField KNR("KNR", 0.0*Mrel);
	
	volScalarField SS("SS", 0.0*Mrel);
	forAll(SS,i)
	{
		SS[i]=min(floor(Mrel[i]-(1.0e-4)),1.0); // mask field for supersonic flow (0 = Mrel<1, 1 = Mrel>=1)
	}
	// the tiny offset is to avoid problems when Mrel = 1.0 exactly
	KNR = (1.0-SS) * (1.0/Foam::sqrt(mag(1.0 - magSqr(Mrel)))) + SS * (4.0/Foam::constant::mathematical::pi)*(1.0/Foam::sqrt(mag(magSqr(Mrel) - 1.0)));

	volVectorField fn("fn", min(KNR,3.0) * (fnmag*sin(DEVLOC)*tabc - fnmag*cos(DEVLOC)*nabc));

	// Viscous profile loss force
	const volScalarField& tmu = mesh.lookupObject<volScalarField>("thermo:mu");
	volScalarField RExc("RExc",max(rho*mag(Wabc)*chordwisePos/tmu,10.0));
	volScalarField Kp0("Kp0", 2.0*0.0592*pow(RExc, -0.2));

//	volVectorField fpv("fpv", -1.0*magSqr(Wabc)*B/(4.0*Foam::constant::mathematical::pi*Radius*max(mag(camber.component(2)),1e-4)) * Wabc / (max(mag(Wabc),smallVelocity)) * (Kp0 + FpCalibrated*2.0*Foam::constant::mathematical::pi*sqr(DEVLOC-Devloc0))); // if order of camber components fixed, change index here
	volVectorField fpv("fpv", -1.0*magSqr(Wabc)/(2.0*max(Radius,smallLength)*max(mag(pitch),1e-4)*max(mag(camber.component(2)),1e-4)) * Wabc / (max(mag(Wabc),smallVelocity)) * (Kp0 + FpCalibrated*2.0*Foam::constant::mathematical::pi*sqr(DEVLOC-Devloc0))); // if order of camber components fixed, change index here
	

	// Shock loss force
	volScalarField ptrel("ptrel", p * pow(1.0 + (gamma-1.0)*0.5*sqr(Mrel),gamma/(gamma-1.0)));
	const dimensionedScalar gammaTerm = (Cv/Rgas)*(2.0*gamma*(gamma-1))/(3.0*sqr(gamma+1));
	
//	volVectorField fps("fps",  -SS*ptrel*gammaTerm*Foam::pow((sqr(Mrel)-1.0),3.0)*B/(2.0*Foam::constant::mathematical::pi*max(Radius,smallLength)*max(mag(camber.component(2)),1e-4)*rho) * (Wabc / (max(mag(Wabc),smallVelocity)))); // if order of camber components fixed, change index here
	volVectorField fps("fps",  -SS*ptrel*gammaTerm*Foam::pow((sqr(Mrel)-1.0),3.0)/(max(Radius,smallLength)*max(mag(pitch),1e-4)*max(mag(camber.component(2)),1e-4)*rho) * (Wabc / (max(mag(Wabc),smallVelocity)))); 
	// Total force in abc
	volVectorField fabc("fabc", fn + fpv + fps );	
	// Total force in xyz
	volVectorField fxyz("fxyz", Rot1 & fabc);
	// compute F
	F = (rho * fxyz / b) * fOut;
