
/* Turbomachinery and Unsteady Flows Research Group | University of Windsor  *\
                    ░░▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒░░░                                 
                 ░▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒░                            
               ░▒▓▓▒▒░░░░▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒░                      
             ░▒▓▓░   ▒▓░    ░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░                  
            ▒▓▓░   ░▒▓▓▓░ ░▓▓▓▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒░               
           ▒▓▒░░░  ░▓▓▓▓▒░▓▓▓▓▒░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒░            
         ░▓▓▒ ░░░░ ░▓▓▓▓▓ ▒▓▓▓▒  ▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒          
         ▒▓▒  ░░░░░ ▒▓▓▓▓░░▓▓▓▒  ░▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒        
        ▓▓▒   ░░░░░░░▓▓▓▓░░▓▓▓▒                        ░░▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓░      
       ▒▓▓░   ░░░░░░ ░▓▓▓▒ ▓▓▓▒       ░░░▒▒▒▒▒▒▒▒▒░░░░          ░░░▒▓▓▓▓▓░     
      ▒▓▓▒░    ░░░░░░ ▒▓▓▒ ▒▓▓▒ ░▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒░░     ▒░     
      ▓▓▓░▓▓▒    ░░░░ ░▓▓▓░▒▓▓▒  ░▓▓▓▓▒░  ▒▓▓▒                   ░▒▒▓▓▓▓▒      
     ▒▓▓░▒▓▓▓▓░   ░░░░ ▒▓▓░░▓▓▒           ▒▓▓▒    ░                      ░░▒▒░ 
    ░▓▓▒ ▒▓▓▓▓▓▒   ░░░░░▓▓░░▓▓▒           ▒▓▓▒    ▒▓  ▒▓░▒▓▓▓▒ ▓▓▓▓░  ░▓▓░     
    ▒▓▓░ ▒▓▓▓▓▓▓▓░  ░░░ ▒▓▒░▓▓░           ▒▓▓▒   ░▒▓  ▓▓░▒▓░   ▓▒░▒▓░▒▓▒░▓▒░   
   ░▒▓▒░ ▒▓▓▓▓▓▓▓▓░ ░░░░░▓▒░▓▓░           ▒▓▓▒   ░▒▓  ▓▓░▒▓▓▓░ ▓▒░▒▓ ▒▓░       
   ░▓▓▒    ░▒▓▓▓▓▓▓▒ ░░░ ▓░░▓▓            ▒▓▓▒   ░▒▓  ▓▒░▒▓░   ▓▓▓▓▒░▒▓░░▓▓░   
   ▒▓▓▒       ░▒▓▓▓▓▒ ░░ ▒░░▓░            ▒▓▓▒   ░▒▓ ░▓▒░▒▓░   ▓▓ ▒▓░▒▓▓▓▓▓░   
   ▒▓▓░▒▒▒░░░    ▒▓▓▓░                    ▒▓▓▒    ░▓▓▓▓░ ▒▓░   ▓▓ ░▓▓  ▓▓      
   ▓▓▓░▓▓▓▓▓▓▓▓▒  ░▒▓░   ░░               ▒▓▓▒                          ░▒▒▒▒░ 
  ░▓▓▓░▓▓▓▓▓▓▓▓▓▓▒░ ░  ░▓▓▓▓▓▓▒▒░░░       ░░░░               ░░░░▒▒▒▓▓▓▒▒░░    
  ░▓▓▒░▓▓▓▓▓▓▓▓▓▓▓▓░  ░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒░            
  ░▒▒░                   ░░▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░                   
\*---------------------------------------------------------------------------*/

    // Set F
    
	volVectorField Uabc("Uabc", Rot & U); // velocity field in abc coordinates -- THIS SEEMS OK
	volVectorField Wabc("Wabc", Uabc - (OMEGA ^ abc)); // relative velocity in abc

	// Normal force	
	volScalarField DEVLOC("DEVLOC", asin((Wabc & nabc) / max(mag(Wabc),smallVelocity))); // local deviation	

	volVectorField WabcN("WabcN", (Wabc & nabc) * nabc); // part of Wabc in nabc direction
	volVectorField WabcT("WabcT", Wabc - WabcN); // rest of Wabc
	volVectorField tabc("tabc", WabcT/max(mag(WabcT),smallVelocity)); // tangential direction

//	volScalarField fnmag("fnmag", 0.5*DEVLOC*magSqr(Wabc)*B/max(Radius,smallLength)/(max(mag(camber.component(2)),1e-4))); // if order of camber components fixed, change index here
	volScalarField fnmag("fnmag", Foam::constant::mathematical::pi*DEVLOC*magSqr(Wabc)/max(Radius,smallLength)/max(mag(pitch),1e-4)/(max(mag(camber.component(2)),1e-4)));

	volVectorField fn("fn", fnmag*sin(DEVLOC)*tabc - fnmag*cos(DEVLOC)*nabc);

	// Viscous profile loss force
	const volScalarField& tnu = turbulence->nu();// ?? // mesh.lookupObject<volScalarField>("thermo:mu");
	volScalarField RExc("RExc",max(mag(Wabc)*chordwisePos/tnu,10.0));
	volScalarField Kp0("Kp0", 2.0*0.0592*pow(RExc, -0.2));

	volVectorField fpv("fpv", -1.0*(magSqr(Wabc)/(2.0*max(Radius,smallLength)*max(mag(pitch),1e-4)*max(mag(camber.component(2)),1e-4))) * Wabc / (max(mag(Wabc),smallVelocity)) * (Kp0 + FpCalibrated*2.0*Foam::constant::mathematical::pi*sqr(DEVLOC-Devloc0))); // if order of camber components fixed, change index here

	// Total force in abc
	volVectorField fabc("fabc", fn + fpv );	
	// Total force in xyz
	volVectorField fxyz("fxyz", Rot1 & fabc);
	// compute F
	F = (fxyz / b) * fOut;
